server:
  port: 9090
spring:
  application:
    name: mayikt-weixin
  cloud:
    nacos:
      discovery:
        ##nacos服务注册地址
        server-addr: 127.0.0.1:8848
swagger:
  base-package: com.mayikt.api.member.service.weixin.api
  title: SpringCloud2.x构建微服务电商项目-微信服务接口
  description: 该项目“基于SpringCloud2.x构建微服务电商项目”。
  version: 1.1
  terms-of-service-url: www.mayikt.com
  contact:
    name: taotao
    email: 644064779@qq.com
    url: www.mayikt.com
  enabled: true
